use std::collections::HashMap;

use crate::ast::{BinaryOp, Type, UnaryOp};
use crate::typed::{
    BuiltinFunction, CallTarget, FunctionId, LocalId, TypedBlock, TypedExpr, TypedExprKind,
    TypedExprType, TypedFunction, TypedLoopPart, TypedProgram, TypedStmt, TypedStmtKind,
};

pub fn emit_windows_x64_asm(program: &TypedProgram) -> Result<String, String> {
    NativeEmitter::new(program).emit_program()
}

struct NativeEmitter<'a> {
    program: &'a TypedProgram,
    functions: HashMap<FunctionId, &'a TypedFunction>,
    string_literals: Vec<(String, String)>,
    label_index: usize,
    current_return_label: String,
    current_local_count: usize,
    current_max_call_args: usize,
    temp_stack_depth: usize,
    loop_stack: Vec<LoopLabels>,
}

#[derive(Debug, Clone)]
struct LoopLabels {
    break_label: String,
    continue_label: String,
}

impl<'a> NativeEmitter<'a> {
    fn new(program: &'a TypedProgram) -> Self {
        let functions = program
            .functions
            .iter()
            .map(|function| (function.function_id, function))
            .collect();

        Self {
            program,
            functions,
            string_literals: Vec::new(),
            label_index: 0,
            current_return_label: String::new(),
            current_local_count: 0,
            current_max_call_args: 0,
            temp_stack_depth: 0,
            loop_stack: Vec::new(),
        }
    }

    fn emit_program(mut self) -> Result<String, String> {
        let mut out = String::new();
        out.push_str("; Generated by Anadil native backend MVP\n");
        out.push_str("option casemap:none\n\n");
        out.push_str("extrn printf:proc\n");
        out.push_str("extrn strcmp:proc\n");
        out.push_str("extrn getchar:proc\n");
        out.push_str("extrn exit:proc\n");
        out.push_str("includelib msvcrt.lib\n\n");
        out.push_str(".data\n");
        out.push_str("fmt_sayi db \"%lld\", 10, 0\n");
        out.push_str("fmt_metin db \"%s\", 10, 0\n");
        out.push_str("fmt_runtime_error db \"%s\", 10, 0\n");
        out.push_str("error_div_zero db \"Sifira bolme hatasi\", 0\n");
        out.push_str("text_dogru db 100, 111, 196, 159, 114, 117, 0\n");
        out.push_str("text_yanlis db 121, 97, 110, 108, 196, 177, 197, 159, 0\n\n");
        out.push_str(".code\n");
        out.push_str("main PROC\n");
        out.push_str("    sub rsp, 40\n");
        out.push_str("    call anadil_fn_Ana\n");
        out.push_str("    call getchar\n");
        out.push_str("    xor eax, eax\n");
        out.push_str("    add rsp, 40\n");
        out.push_str("    ret\n");
        out.push_str("main ENDP\n\n");

        let functions: Vec<_> = self.program.functions.iter().collect();
        for function in functions {
            self.emit_function(function, &mut out)?;
        }

        if !self.string_literals.is_empty() {
            out.push_str(".data\n");
            for (label, value) in &self.string_literals {
                out.push_str(label);
                out.push_str(" db ");
                out.push_str(&encode_db_string(value));
                out.push_str(", 0\n");
            }
        }

        out.push_str("\nEND\n");
        Ok(out)
    }

    fn emit_function(&mut self, function: &TypedFunction, out: &mut String) -> Result<(), String> {
        let local_count = local_count(function);
        let max_call_args = max_call_args(function);
        let frame_size = align_to((local_count + max_call_args) * 8, 16);
        let return_label = self.fresh_label("return");
        self.current_return_label = return_label.clone();
        self.current_local_count = local_count;
        self.current_max_call_args = max_call_args;
        self.temp_stack_depth = 0;

        out.push_str(&format!("{} PROC\n", function_label(function)));
        out.push_str("    push rbp\n");
        out.push_str("    mov rbp, rsp\n");
        out.push_str(&format!("    sub rsp, {frame_size}\n"));

        for (index, param) in function.params.iter().enumerate() {
            if let Some(reg) = param_register(index) {
                out.push_str(&format!(
                    "    mov QWORD PTR [rbp-{}], {reg}\n",
                    local_offset(param.local_id)
                ));
            } else {
                let stack_offset = stack_param_offset(index);
                out.push_str(&format!("    mov rax, QWORD PTR [rbp+{stack_offset}]\n"));
                out.push_str(&format!(
                    "    mov QWORD PTR [rbp-{}], rax\n",
                    local_offset(param.local_id)
                ));
            }
        }

        self.emit_block(&function.body, out)?;
        out.push_str("    xor rax, rax\n");
        out.push_str(&format!("{return_label}:\n"));
        out.push_str(&format!("    add rsp, {frame_size}\n"));
        out.push_str("    pop rbp\n");
        out.push_str("    ret\n");
        out.push_str(&format!("{} ENDP\n\n", function_label(function)));
        self.temp_stack_depth = 0;
        Ok(())
    }

    fn emit_block(&mut self, block: &TypedBlock, out: &mut String) -> Result<(), String> {
        for statement in &block.statements {
            self.emit_statement(statement, out)?;
        }
        Ok(())
    }

    fn emit_statement(&mut self, statement: &TypedStmt, out: &mut String) -> Result<(), String> {
        match &statement.kind {
            TypedStmtKind::VarDecl(decl) => {
                self.emit_expr(&decl.value, out)?;
                out.push_str(&format!(
                    "    mov QWORD PTR [rbp-{}], rax\n",
                    local_offset(decl.local_id)
                ));
            }
            TypedStmtKind::Assign(assign) => {
                self.emit_expr(&assign.value, out)?;
                out.push_str(&format!(
                    "    mov QWORD PTR [rbp-{}], rax\n",
                    local_offset(assign.target.id)
                ));
            }
            TypedStmtKind::Expr(expr) => {
                self.emit_expr(expr, out)?;
            }
            TypedStmtKind::Return(value) => {
                if let Some(value) = value {
                    self.emit_expr(value, out)?;
                } else {
                    out.push_str("    xor rax, rax\n");
                }
                out.push_str(&format!("    jmp {}\n", self.current_return_label));
            }
            TypedStmtKind::If(if_stmt) => {
                let else_label = self.fresh_label("else");
                let end_label = self.fresh_label("endif");
                self.emit_expr(&if_stmt.condition, out)?;
                out.push_str("    cmp rax, 0\n");
                out.push_str(&format!("    je {else_label}\n"));
                self.emit_block(&if_stmt.then_branch, out)?;
                out.push_str(&format!("    jmp {end_label}\n"));
                out.push_str(&format!("{else_label}:\n"));
                if let Some(else_branch) = &if_stmt.else_branch {
                    self.emit_block(else_branch, out)?;
                }
                out.push_str(&format!("{end_label}:\n"));
            }
            TypedStmtKind::Loop(loop_stmt) => {
                if let Some(init) = &loop_stmt.init {
                    self.emit_loop_part(init, out)?;
                }

                let start_label = self.fresh_label("loop");
                let continue_label = self.fresh_label("loop_continue");
                let break_label = self.fresh_label("loop_break");
                self.loop_stack.push(LoopLabels {
                    break_label: break_label.clone(),
                    continue_label: continue_label.clone(),
                });

                out.push_str(&format!("{start_label}:\n"));
                if let Some(condition) = &loop_stmt.condition {
                    self.emit_expr(condition, out)?;
                    out.push_str("    cmp rax, 0\n");
                    out.push_str(&format!("    je {break_label}\n"));
                }

                self.emit_block(&loop_stmt.body, out)?;
                out.push_str(&format!("{continue_label}:\n"));
                if let Some(step) = &loop_stmt.step {
                    self.emit_loop_part(step, out)?;
                }
                out.push_str(&format!("    jmp {start_label}\n"));
                out.push_str(&format!("{break_label}:\n"));
                self.loop_stack.pop();
            }
            TypedStmtKind::Break => {
                let labels = self
                    .loop_stack
                    .last()
                    .ok_or("native codegen icinde loop etiketi bulunamadi")?;
                out.push_str(&format!("    jmp {}\n", labels.break_label));
            }
            TypedStmtKind::Continue => {
                let labels = self
                    .loop_stack
                    .last()
                    .ok_or("native codegen icinde loop etiketi bulunamadi")?;
                out.push_str(&format!("    jmp {}\n", labels.continue_label));
            }
        }
        Ok(())
    }

    fn emit_loop_part(&mut self, part: &TypedLoopPart, out: &mut String) -> Result<(), String> {
        match part {
            TypedLoopPart::VarDecl(decl) => {
                self.emit_expr(&decl.value, out)?;
                out.push_str(&format!(
                    "    mov QWORD PTR [rbp-{}], rax\n",
                    local_offset(decl.local_id)
                ));
            }
            TypedLoopPart::Assign(assign) => {
                self.emit_expr(&assign.value, out)?;
                out.push_str(&format!(
                    "    mov QWORD PTR [rbp-{}], rax\n",
                    local_offset(assign.target.id)
                ));
            }
            TypedLoopPart::Expr(expr) => {
                self.emit_expr(expr, out)?;
            }
        }
        Ok(())
    }

    fn emit_expr(&mut self, expr: &TypedExpr, out: &mut String) -> Result<(), String> {
        match &expr.kind {
            TypedExprKind::Number(value) => out.push_str(&format!("    mov rax, {value}\n")),
            TypedExprKind::Bool(value) => {
                out.push_str(&format!("    mov rax, {}\n", if *value { 1 } else { 0 }));
            }
            TypedExprKind::String(value) => {
                let label = self.intern_string(value);
                out.push_str(&format!("    lea rax, {label}\n"));
            }
            TypedExprKind::Variable(local) => {
                out.push_str(&format!(
                    "    mov rax, QWORD PTR [rbp-{}]\n",
                    local_offset(local.id)
                ));
            }
            TypedExprKind::Unary { op, expr } => {
                self.emit_expr(expr, out)?;
                match op {
                    UnaryOp::Negate => out.push_str("    neg rax\n"),
                }
            }
            TypedExprKind::Binary { left, op, right } => {
                self.emit_binary_expr(left, *op, right, expr.ty, out)?;
            }
            TypedExprKind::Call { target, args } => self.emit_call(target, args, expr.ty, out)?,
        }
        Ok(())
    }

    fn emit_binary_expr(
        &mut self,
        left: &TypedExpr,
        op: BinaryOp,
        right: &TypedExpr,
        result_type: TypedExprType,
        out: &mut String,
    ) -> Result<(), String> {
        if is_string_equality(left, op, right) {
            self.emit_expr(left, out)?;
            self.emit_push_rax(out);
            self.emit_expr(right, out)?;
            out.push_str("    mov rdx, rax\n");
            self.emit_pop_into("rcx", out);
            let call_area_size = self.emit_reserve_call_area(0, out);
            out.push_str("    call strcmp\n");
            self.emit_release_call_area(call_area_size, out);
            out.push_str("    cmp eax, 0\n");
            out.push_str(match op {
                BinaryOp::Equal => "    sete al\n",
                BinaryOp::NotEqual => "    setne al\n",
                _ => unreachable!(),
            });
            out.push_str("    movzx rax, al\n");
            return Ok(());
        }

        self.emit_expr(left, out)?;
        self.emit_push_rax(out);
        self.emit_expr(right, out)?;
        out.push_str("    mov r10, rax\n");
        self.emit_pop_into("rax", out);

        match op {
            BinaryOp::Add => out.push_str("    add rax, r10\n"),
            BinaryOp::Subtract => out.push_str("    sub rax, r10\n"),
            BinaryOp::Multiply => out.push_str("    imul rax, r10\n"),
            BinaryOp::Divide => {
                let ok_label = self.fresh_label("div_ok");
                out.push_str("    cmp r10, 0\n");
                out.push_str(&format!("    jne {ok_label}\n"));
                out.push_str("    lea rcx, fmt_runtime_error\n");
                out.push_str("    lea rdx, error_div_zero\n");
                let printf_area_size = self.emit_reserve_call_area(0, out);
                out.push_str("    call printf\n");
                self.emit_release_call_area(printf_area_size, out);
                let wait_area_size = self.emit_reserve_call_area(0, out);
                out.push_str("    call getchar\n");
                self.emit_release_call_area(wait_area_size, out);
                out.push_str("    mov ecx, 1\n");
                let exit_area_size = self.emit_reserve_call_area(0, out);
                out.push_str("    call exit\n");
                self.emit_release_call_area(exit_area_size, out);
                out.push_str(&format!("{ok_label}:\n"));
                out.push_str("    cqo\n");
                out.push_str("    idiv r10\n");
            }
            BinaryOp::Equal
            | BinaryOp::NotEqual
            | BinaryOp::Less
            | BinaryOp::Greater
            | BinaryOp::LessEqual
            | BinaryOp::GreaterEqual => {
                out.push_str("    cmp rax, r10\n");
                let set_op = match op {
                    BinaryOp::Equal => "sete",
                    BinaryOp::NotEqual => "setne",
                    BinaryOp::Less => "setl",
                    BinaryOp::Greater => "setg",
                    BinaryOp::LessEqual => "setle",
                    BinaryOp::GreaterEqual => "setge",
                    _ => unreachable!(),
                };
                out.push_str(&format!("    {set_op} al\n"));
                out.push_str("    movzx rax, al\n");
            }
        }

        if result_type == TypedExprType::Void {
            return Err("native codegen void binary expression uretmemeli".to_string());
        }
        Ok(())
    }

    fn emit_call(
        &mut self,
        target: &CallTarget,
        args: &[TypedExpr],
        _result_type: TypedExprType,
        out: &mut String,
    ) -> Result<(), String> {
        match target {
            CallTarget::Builtin(BuiltinFunction::Yazdir) => {
                let arg = args
                    .first()
                    .ok_or("`yazdir` native codegen icin bir arguman bekler")?;
                self.emit_yazdir(arg, out)
            }
            CallTarget::Function { function_id, name } => {
                if args.len() > self.current_max_call_args {
                    return Err(format!(
                        "native codegen call scratch alani yetersiz: `{name}` {} arguman",
                        args.len()
                    ));
                }

                for arg in args {
                    self.emit_expr(arg, out)?;
                    self.emit_push_rax(out);
                }

                for index in (0..args.len()).rev() {
                    self.emit_pop_into("rax", out);
                    out.push_str(&format!(
                        "    mov QWORD PTR [rbp-{}], rax\n",
                        call_arg_offset(self.current_local_count, index)
                    ));
                }

                let stack_arg_count = args.len().saturating_sub(4);
                let call_area_size = self.emit_reserve_call_area(stack_arg_count, out);

                for index in 0..args.len().min(4) {
                    let reg = param_register(index).expect("first four args use registers");
                    out.push_str(&format!(
                        "    mov {reg}, QWORD PTR [rbp-{}]\n",
                        call_arg_offset(self.current_local_count, index)
                    ));
                }

                for index in 4..args.len() {
                    out.push_str(&format!(
                        "    mov rax, QWORD PTR [rbp-{}]\n",
                        call_arg_offset(self.current_local_count, index)
                    ));
                    out.push_str(&format!(
                        "    mov QWORD PTR [rsp+{}], rax\n",
                        32 + (index - 4) * 8
                    ));
                }

                let call_result = (|| {
                    let function = self
                        .functions
                        .get(function_id)
                        .ok_or_else(|| format!("Fonksiyon bulunamadi: `{name}`"))?;
                    out.push_str(&format!("    call {}\n", function_label(function)));
                    Ok(())
                })();
                self.emit_release_call_area(call_area_size, out);
                call_result
            }
        }
    }

    fn emit_push_rax(&mut self, out: &mut String) {
        out.push_str("    push rax\n");
        self.temp_stack_depth += 1;
    }

    fn emit_pop_into(&mut self, register: &str, out: &mut String) {
        out.push_str(&format!("    pop {register}\n"));
        self.temp_stack_depth = self
            .temp_stack_depth
            .checked_sub(1)
            .expect("native temp stack pop without push");
    }

    fn emit_reserve_call_area(&self, stack_arg_count: usize, out: &mut String) -> usize {
        let raw_size = 32 + stack_arg_count * 8;
        let align_padding = if (self.temp_stack_depth + stack_arg_count).is_multiple_of(2) {
            0
        } else {
            8
        };
        let call_area_size = raw_size + align_padding;

        out.push_str(&format!("    sub rsp, {call_area_size}\n"));
        call_area_size
    }

    fn emit_release_call_area(&self, call_area_size: usize, out: &mut String) {
        out.push_str(&format!("    add rsp, {call_area_size}\n"));
    }

    fn emit_yazdir(&mut self, arg: &TypedExpr, out: &mut String) -> Result<(), String> {
        self.emit_expr(arg, out)?;
        match value_type(arg)? {
            Type::Sayi => {
                out.push_str("    lea rcx, fmt_sayi\n");
                out.push_str("    mov rdx, rax\n");
            }
            Type::Mantik => {
                let false_label = self.fresh_label("bool_false");
                let end_label = self.fresh_label("bool_done");
                out.push_str("    cmp rax, 0\n");
                out.push_str(&format!("    je {false_label}\n"));
                out.push_str("    lea rdx, text_dogru\n");
                out.push_str(&format!("    jmp {end_label}\n"));
                out.push_str(&format!("{false_label}:\n"));
                out.push_str("    lea rdx, text_yanlis\n");
                out.push_str(&format!("{end_label}:\n"));
                out.push_str("    lea rcx, fmt_metin\n");
            }
            Type::Metin => {
                out.push_str("    lea rcx, fmt_metin\n");
                out.push_str("    mov rdx, rax\n");
            }
        }
        let call_area_size = self.emit_reserve_call_area(0, out);
        out.push_str("    call printf\n");
        self.emit_release_call_area(call_area_size, out);
        Ok(())
    }

    fn intern_string(&mut self, value: &str) -> String {
        let label = format!("str_{}", self.string_literals.len());
        self.string_literals
            .push((label.clone(), value.to_string()));
        label
    }

    fn fresh_label(&mut self, prefix: &str) -> String {
        let label = format!("L_{prefix}_{}", self.label_index);
        self.label_index += 1;
        label
    }
}

fn function_label(function: &TypedFunction) -> String {
    format!("anadil_fn_{}", function.name)
}

fn local_offset(id: LocalId) -> usize {
    (id.0 + 1) * 8
}

fn call_arg_offset(local_count: usize, index: usize) -> usize {
    (local_count + index + 1) * 8
}

fn local_count(function: &TypedFunction) -> usize {
    let mut max_id = 0usize;
    for param in &function.params {
        max_id = max_id.max(param.local_id.0 + 1);
    }
    collect_block_local_count(&function.body, &mut max_id);
    max_id
}

fn collect_block_local_count(block: &TypedBlock, max_id: &mut usize) {
    for statement in &block.statements {
        match &statement.kind {
            TypedStmtKind::VarDecl(decl) => *max_id = (*max_id).max(decl.local_id.0 + 1),
            TypedStmtKind::If(if_stmt) => {
                collect_block_local_count(&if_stmt.then_branch, max_id);
                if let Some(else_branch) = &if_stmt.else_branch {
                    collect_block_local_count(else_branch, max_id);
                }
            }
            TypedStmtKind::Loop(loop_stmt) => {
                if let Some(part) = &loop_stmt.init {
                    collect_loop_part_local_count(part, max_id);
                }
                if let Some(part) = &loop_stmt.step {
                    collect_loop_part_local_count(part, max_id);
                }
                collect_block_local_count(&loop_stmt.body, max_id);
            }
            _ => {}
        }
    }
}

fn collect_loop_part_local_count(part: &TypedLoopPart, max_id: &mut usize) {
    if let TypedLoopPart::VarDecl(decl) = part {
        *max_id = (*max_id).max(decl.local_id.0 + 1);
    }
}

fn max_call_args(function: &TypedFunction) -> usize {
    let mut max_args = 0usize;
    collect_block_call_args(&function.body, &mut max_args);
    max_args
}

fn collect_block_call_args(block: &TypedBlock, max_args: &mut usize) {
    for statement in &block.statements {
        match &statement.kind {
            TypedStmtKind::VarDecl(decl) => collect_expr_call_args(&decl.value, max_args),
            TypedStmtKind::Assign(assign) => {
                collect_expr_call_args(&assign.value, max_args);
            }
            TypedStmtKind::If(if_stmt) => {
                collect_expr_call_args(&if_stmt.condition, max_args);
                collect_block_call_args(&if_stmt.then_branch, max_args);
                if let Some(else_branch) = &if_stmt.else_branch {
                    collect_block_call_args(else_branch, max_args);
                }
            }
            TypedStmtKind::Loop(loop_stmt) => {
                if let Some(init) = &loop_stmt.init {
                    collect_loop_part_call_args(init, max_args);
                }
                if let Some(condition) = &loop_stmt.condition {
                    collect_expr_call_args(condition, max_args);
                }
                if let Some(step) = &loop_stmt.step {
                    collect_loop_part_call_args(step, max_args);
                }
                collect_block_call_args(&loop_stmt.body, max_args);
            }
            TypedStmtKind::Return(Some(expr)) | TypedStmtKind::Expr(expr) => {
                collect_expr_call_args(expr, max_args);
            }
            TypedStmtKind::Break | TypedStmtKind::Continue | TypedStmtKind::Return(None) => {}
        }
    }
}

fn collect_loop_part_call_args(part: &TypedLoopPart, max_args: &mut usize) {
    match part {
        TypedLoopPart::VarDecl(decl) => collect_expr_call_args(&decl.value, max_args),
        TypedLoopPart::Assign(assign) => collect_expr_call_args(&assign.value, max_args),
        TypedLoopPart::Expr(expr) => collect_expr_call_args(expr, max_args),
    }
}

fn collect_expr_call_args(expr: &TypedExpr, max_args: &mut usize) {
    match &expr.kind {
        TypedExprKind::Call { args, .. } => {
            *max_args = (*max_args).max(args.len());
            for arg in args {
                collect_expr_call_args(arg, max_args);
            }
        }
        TypedExprKind::Unary { expr, .. } => collect_expr_call_args(expr, max_args),
        TypedExprKind::Binary { left, right, .. } => {
            collect_expr_call_args(left, max_args);
            collect_expr_call_args(right, max_args);
        }
        TypedExprKind::Number(_)
        | TypedExprKind::Bool(_)
        | TypedExprKind::String(_)
        | TypedExprKind::Variable(_) => {}
    }
}

fn param_register(index: usize) -> Option<&'static str> {
    match index {
        0 => Some("rcx"),
        1 => Some("rdx"),
        2 => Some("r8"),
        3 => Some("r9"),
        _ => None,
    }
}

fn stack_param_offset(index: usize) -> usize {
    48 + (index - 4) * 8
}

fn align_to(value: usize, align: usize) -> usize {
    value.div_ceil(align) * align
}

fn value_type(expr: &TypedExpr) -> Result<Type, String> {
    match expr.ty {
        TypedExprType::Value(ty) => Ok(ty),
        TypedExprType::Void => Err("native codegen void degeri yazdiramaz".to_string()),
    }
}

fn is_string_equality(left: &TypedExpr, op: BinaryOp, right: &TypedExpr) -> bool {
    matches!(op, BinaryOp::Equal | BinaryOp::NotEqual)
        && matches!(left.ty, TypedExprType::Value(Type::Metin))
        && matches!(right.ty, TypedExprType::Value(Type::Metin))
}

fn encode_db_string(value: &str) -> String {
    let mut parts = Vec::new();
    let mut current = String::new();

    for byte in value.bytes() {
        match byte {
            b'"' | b'\\' | 0..=31 | 127..=255 => {
                if !current.is_empty() {
                    parts.push(format!("\"{}\"", current));
                    current.clear();
                }
                parts.push(byte.to_string());
            }
            _ => current.push(byte as char),
        }
    }

    if !current.is_empty() {
        parts.push(format!("\"{}\"", current));
    }

    if parts.is_empty() {
        "0".to_string()
    } else {
        parts.join(", ")
    }
}

#[cfg(test)]
mod tests {
    use crate::{compile_source, native::emit_windows_x64_asm};

    #[test]
    fn emits_native_assembly_for_basic_program() {
        let source = "\
Topla(a: say\u{0131}, b: say\u{0131}) -> say\u{0131} {\n\
    d\u{00f6}n a + b;\n\
}

Ana() {
    sonuc: say\u{0131} = Topla(10, 20);\n\
    yazdir(sonuc);\n\
}
";

        let program = compile_source(source).expect("program should compile");
        let asm = emit_windows_x64_asm(&program).expect("assembly should be emitted");

        assert!(asm.contains("main PROC"));
        assert!(asm.contains("anadil_fn_Topla PROC"));
        assert!(asm.contains("call anadil_fn_Topla"));
        assert!(asm.contains("call printf"));
        assert!(asm.contains("call getchar"));
    }
}
